### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by markushinz**
* Adds tests for all packages
* Refactor code for increased testability
* [WIP] Travis CI

### CODE REVIEW

**Comment by nicmr** [comment]
What is the purpose of the whole `type measures map[classification]func(gitlab.Project)` approach?

All that's done later is call `measures[classificationInactive](project)` and `measures[classificationNone](project)` .

What advantages does it offer opposed to, say,
- simply creating two separate functions `measuresInactive(gitlab.Project)` and `measuresNone(gitlab.Project)` and calling them there?
- or, as more flexible approach, passing the functions as parameters?

**Comment by cheld** [comment]
The render.go file is part of housekeeping package. Shouldn't it be part of mail package? WDYT?

**Comment by markushinz** [comment]
> What is the purpose of the whole `type measures map[classification]func(gitlab.Project)` approach?
> 
> All that's done later is call `measures[classificationInactive](project)` and `measures[classificationNone](project)` .
> 
> What advantages does it offer opposed to, say,
> 
> * simply creating two separate functions `measuresInactive(gitlab.Project)` and `measuresNone(gitlab.Project)` and calling them there?
> * or, as more flexible approach, passing the functions as parameters?

The idea was to seperate the classification of projects from the actions that are perfomed on a "class" of projects. This allows us to use different "measures" in `housekeeping_test.go` thus making the classification testable. I used the "map approach" as it is verly likely that there will be more "classifications" than "Inactive" and "None" in the future. Passing one object is cleaner than passing multiple functions, in my opinion.



> The render.go file is part of housekeeping package. Shouldn't it be part of mail package? WDYT?

`render.go` renders arbitary text templates to string. You are right, this functionality is currently only used to create mail bodies but may also be useful in other parts of the application at a later point. I would therefore vote against merging it with the mail pacakge.

**Comment by markushinz** [comment]
Travis issues are resolved.

**Comment by nicmr** [comment]
> The idea was to seperate the classification of projects from the actions that are perfomed on a "class" of projects. This allows us to use different "measures" in `housekeeping_test.go` thus making the classification testable. I used the "map approach" as it is verly likely that there will be more "classifications" than "Inactive" and "None" in the future. Passing one object is cleaner than passing multiple functions, in my opinion.


Thanks, now I get what you're trying to achieve.
I'd suggest a different solution:
```
type Measure struct {
  None func(gitlab.Project)
  Inactive func(gitlab.Project)
}
```
This completely prevents invalid string keys from being used. It still fulfills your requirement of passing only a single struct.

**Pull request merged**
